/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace TodoMapping {
  export type TodoStruct = {
    title: string;
    description: string;
    status: boolean;
  };

  export type TodoStructOutput = [
    title: string,
    description: string,
    status: boolean
  ] & { title: string; description: string; status: boolean };
}

export interface TodoMappingInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "create_todo"
      | "delete_todo"
      | "get_todos"
      | "toggle_todo_status"
      | "update_todo"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "create_todo",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "delete_todo",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "get_todos", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "toggle_todo_status",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "update_todo",
    values: [BigNumberish, string, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "create_todo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "delete_todo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "get_todos", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "toggle_todo_status",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "update_todo",
    data: BytesLike
  ): Result;
}

export interface TodoMapping extends BaseContract {
  connect(runner?: ContractRunner | null): TodoMapping;
  waitForDeployment(): Promise<this>;

  interface: TodoMappingInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  create_todo: TypedContractMethod<
    [_title: string, _description: string],
    [void],
    "nonpayable"
  >;

  delete_todo: TypedContractMethod<
    [_index: BigNumberish],
    [void],
    "nonpayable"
  >;

  get_todos: TypedContractMethod<[], [TodoMapping.TodoStructOutput[]], "view">;

  toggle_todo_status: TypedContractMethod<
    [_index: BigNumberish],
    [void],
    "nonpayable"
  >;

  update_todo: TypedContractMethod<
    [_index: BigNumberish, _new_title: string, _new_description: string],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "create_todo"
  ): TypedContractMethod<
    [_title: string, _description: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "delete_todo"
  ): TypedContractMethod<[_index: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "get_todos"
  ): TypedContractMethod<[], [TodoMapping.TodoStructOutput[]], "view">;
  getFunction(
    nameOrSignature: "toggle_todo_status"
  ): TypedContractMethod<[_index: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "update_todo"
  ): TypedContractMethod<
    [_index: BigNumberish, _new_title: string, _new_description: string],
    [void],
    "nonpayable"
  >;

  filters: {};
}
