/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { MultiSigFactory__factory } from "./MultiSigFactory__factory";
export { MultiSigWallet__factory } from "./MultiSigWallet__factory";
