/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface MultiSigFactoryInterface extends Interface {
  getFunction(
    nameOrSignature: "createWallet" | "deployedWallets" | "getWallets"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "WalletCreated"): EventFragment;

  encodeFunctionData(
    functionFragment: "createWallet",
    values: [AddressLike[], BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "deployedWallets",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getWallets",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "createWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deployedWallets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getWallets", data: BytesLike): Result;
}

export namespace WalletCreatedEvent {
  export type InputTuple = [walletAddress: AddressLike];
  export type OutputTuple = [walletAddress: string];
  export interface OutputObject {
    walletAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MultiSigFactory extends BaseContract {
  connect(runner?: ContractRunner | null): MultiSigFactory;
  waitForDeployment(): Promise<this>;

  interface: MultiSigFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createWallet: TypedContractMethod<
    [_owners: AddressLike[], _requiredApprovals: BigNumberish],
    [void],
    "nonpayable"
  >;

  deployedWallets: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  getWallets: TypedContractMethod<[], [string[]], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createWallet"
  ): TypedContractMethod<
    [_owners: AddressLike[], _requiredApprovals: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "deployedWallets"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getWallets"
  ): TypedContractMethod<[], [string[]], "view">;

  getEvent(
    key: "WalletCreated"
  ): TypedContractEvent<
    WalletCreatedEvent.InputTuple,
    WalletCreatedEvent.OutputTuple,
    WalletCreatedEvent.OutputObject
  >;

  filters: {
    "WalletCreated(address)": TypedContractEvent<
      WalletCreatedEvent.InputTuple,
      WalletCreatedEvent.OutputTuple,
      WalletCreatedEvent.OutputObject
    >;
    WalletCreated: TypedContractEvent<
      WalletCreatedEvent.InputTuple,
      WalletCreatedEvent.OutputTuple,
      WalletCreatedEvent.OutputObject
    >;
  };
}
