/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as employeeSol from "./Employee.sol";
export type { employeeSol };
export type { IEmployee } from "./IEmployee";
export * as factories from "./factories";
export type { EmployeeManager } from "./Employee.sol/EmployeeManager";
export { EmployeeManager__factory } from "./factories/Employee.sol/EmployeeManager__factory";
export { IEmployee__factory } from "./factories/IEmployee__factory";
