/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace AccessGarage {
  export type EmployeeStruct = {
    name: string;
    role: BigNumberish;
    isEmployed: boolean;
    wallet: AddressLike;
  };

  export type EmployeeStructOutput = [
    name: string,
    role: bigint,
    isEmployed: boolean,
    wallet: string
  ] & { name: string; role: bigint; isEmployed: boolean; wallet: string };
}

export interface AccessGarageInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "UpdateOraddEmployee"
      | "canAccessGarage"
      | "getAllEmployees"
      | "getEmployee"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "UpdateOraddEmployee",
    values: [AddressLike, string, BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "canAccessGarage",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllEmployees",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getEmployee",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "UpdateOraddEmployee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "canAccessGarage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllEmployees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEmployee",
    data: BytesLike
  ): Result;
}

export interface AccessGarage extends BaseContract {
  connect(runner?: ContractRunner | null): AccessGarage;
  waitForDeployment(): Promise<this>;

  interface: AccessGarageInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  UpdateOraddEmployee: TypedContractMethod<
    [
      _wallet: AddressLike,
      _name: string,
      _role: BigNumberish,
      _isEmployed: boolean
    ],
    [void],
    "nonpayable"
  >;

  canAccessGarage: TypedContractMethod<
    [_wallet: AddressLike],
    [boolean],
    "view"
  >;

  getAllEmployees: TypedContractMethod<
    [],
    [AccessGarage.EmployeeStructOutput[]],
    "view"
  >;

  getEmployee: TypedContractMethod<
    [_wallet: AddressLike],
    [
      [string, bigint, boolean, string] & {
        name: string;
        role: bigint;
        isEmployed: boolean;
        wallet: string;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "UpdateOraddEmployee"
  ): TypedContractMethod<
    [
      _wallet: AddressLike,
      _name: string,
      _role: BigNumberish,
      _isEmployed: boolean
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "canAccessGarage"
  ): TypedContractMethod<[_wallet: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "getAllEmployees"
  ): TypedContractMethod<[], [AccessGarage.EmployeeStructOutput[]], "view">;
  getFunction(
    nameOrSignature: "getEmployee"
  ): TypedContractMethod<
    [_wallet: AddressLike],
    [
      [string, bigint, boolean, string] & {
        name: string;
        role: bigint;
        isEmployed: boolean;
        wallet: string;
      }
    ],
    "view"
  >;

  filters: {};
}
