/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AccessGarage } from "./AccessGarage";
export * as factories from "./factories";
export { AccessGarage__factory } from "./factories/AccessGarage__factory";
