/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Smanagement } from "./Smanagement";
export * as factories from "./factories";
export { Smanagement__factory } from "./factories/Smanagement__factory";
