/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Schoolm } from "./Schoolm";
export * as factories from "./factories";
export { Schoolm__factory } from "./factories/Schoolm__factory";
